sundeckenergy/init_package/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('website.urls'))
]

sundeckenergy/website/urls.py
from django.conf.urls import url
from . import views

app_name = 'website'
urlpatterns = [
    #contactus/
    url(r'^$', views.homeView, name='home_view'),
    url(r'^about-us/$', views.aboutusView, name='about_view'),
    url(r'^gallery/$', views.galleryView, name='gallery_view'),
    url(r'^contact-us/$', views.contactusView, name='contact_view'),
]

sundeckenergy/website/models.py
from django.db import models
from django.core.validators import RegexValidator
from django import forms
from datetime import datetime
#from django.utils import timezone
from pytz import timezone

class Customer(models.Model):
    name = models.CharField(max_length = 100)
    email = models.EmailField(max_length = 100)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    mobileNum = models.CharField(validators=[phone_regex], max_length=15, blank=True)
    roofType = models.CharField(max_length = 50)
    roofHeight = models.CharField(max_length = 20)
    electricityBoard = models.CharField(max_length = 100)
    otherDetails = models.TextField(max_length = 2000)
    address = models.CharField(max_length = 300)
    latitude = models.CharField(max_length = 30)
    longitude = models.CharField(max_length = 30)
    create_tmp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        create_tmp = self.create_tmp.astimezone(timezone('Asia/Kolkata'))
        return self.name + " - " + create_tmp.strftime('%d/%b/%Y %I:%M:%S %p')

sundeckenergy/website/forms.py
from django import forms
from .models import Customer

class CustomerForm(forms.Form):
    name = forms.CharField(label = "Name*", max_length = 100,
                          widget = forms.TextInput(attrs = {'placeholder' : 'Name', 'type' : 'text'}))
    email = forms.EmailField(label = "E-mail*", max_length = 100, required = True,
                          widget = forms.TextInput(attrs = {'placeholder' : 'E-Mail Id', 'type' : 'email'}))
    mobileNum = forms.CharField(label = "Phone Number*", max_length= 25, required = True,
                          widget = forms.TextInput(attrs = {'placeholder' : 'Phone Number', 'type' : 'text'}))
    roofType = forms.CharField(label = "Roof Type*", max_length = 50, required = True,
                          widget = forms.TextInput(attrs = {'placeholder' : 'Roof Type', 'type' : 'text'}))
    roofHeight = forms.CharField(label = "Roof Height*", max_length = 20, required = True,
                          widget = forms.TextInput(attrs = {'placeholder' : 'Roof Height', 'type' : 'text'}))
    electricityBoard = forms.CharField(label = "Electricity Board*", max_length = 100, required = True,
                          widget = forms.TextInput(attrs = {'placeholder' : 'Electricity Board', 'type' : 'text'}))
    otherDetails = forms.CharField(label = "Any Other Details*",
                          widget=forms.Textarea(attrs= {'placeholder' : 'Other Details'}))
    address = forms.CharField(label = "Address*", max_length = 300,
                          widget = forms.TextInput(attrs = {'placeholder' : 'Address', 'type' : 'text'}))
    latitude = forms.CharField(label = "Latitude*", max_length = 20, required = True,
                          widget = forms.TextInput(attrs = {'placeholder' : 'Latitude', 'type' : 'text', 'disabled' : ''}))
    longitude = forms.CharField(label = "Longitude*", max_length = 20, required = True,
                          widget = forms.TextInput(attrs = {'placeholder' : 'Longitude', 'type' : 'text', 'disabled' : ''}))

sundeckenergy/website/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Customer
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Context, loader
from .forms import CustomerForm
from django.views.generic.edit import CreateView
from . import forms
from pytz import timezone
from django.core.mail import send_mail

class BaseView(generic.DetailView):
    model = Customer
    template_name='website/base.html'

def homeView(request):
    template = loader.get_template('website/index.html')
    return HttpResponse(template.render(None,request))

def aboutusView(request):
    template = loader.get_template('website/aboutus.html')
    return HttpResponse(template.render(None,request))

def galleryView(request):
    template = loader.get_template('website/gallery.html')
    return HttpResponse(template.render(None,request))

def contactusView(request):
    template = loader.get_template('website/contactus.html')
    return HttpResponse(template.render(None,request))

def contactusView(request):
    if request.method == "GET" :
        form = CustomerForm()
    else :
        form = CustomerForm(request.POST)
        customer = Customer()
        customer.name = request.POST.get("name")
        customer.email = request.POST.get("email")
        customer.mobileNum = request.POST.get("mobileNum")
        customer.roofType = request.POST.get("roofType")
        customer.roofHeight = request.POST.get("roofHeight")
        customer.electricityBoard = request.POST.get("electricityBoard")
        customer.otherDetails = request.POST.get("otherDetails")
        customer.address = request.POST.get("address")
        customer.latitude = request.POST.get("latitude")
        customer.longitude = request.POST.get("longitude")
        customer.save()
        message = 'Name : {name} \nEmail : {email} \nMobile : {mob} \nRoof Type : {roofType} \nRoof Height : {roofHeight} \nElectricity Board : {eboard} \nOther Details : {details} \nAddress : {addr} \nLatitide : {lat} \nLongitude : {lon}'.format(name=customer.name, email=customer.email, mob=customer.mobileNum, roofType=customer.roofType, roofHeight=customer.roofHeight, eboard=customer.electricityBoard, details=customer.otherDetails, addr=customer.address, lat=customer.latitude, lon=customer.longitude,)
        send_mail(customer.name + ' has sent you a query!!!' , message, 'amitm20692@gmail.com', ['abhi.rocks1289@gmail.com','amitm20692@gmail.com'], fail_silently=False,)
        return render(request, "website/index.html", {'success_status' : "success", 'contact_name' : request.POST.get("name")})
    return render(request, "website/contact.html", {'form': form})

sundeckenergy/website/templates/website/base.html
<html>
<head>
  <title> {%block title%}  {%endblock%} </title>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!--Loading Static Files-->
  {%load staticfiles%}

  <!-- Meta tag Keywords -->
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  	<meta name="keywords" content="Solar Power, PV , Photovoltaic , Solar Awareness, Indian Government policies for Solar, Rooftop Solar implementation, Off Grid , In Grid"
  	/>
  	<script type="application/x-javascript">
  		addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
  function hideURLbar(){ window.scrollTo(0,1); }
	</script>
	<!--// Meta tag Keywords -->
	<!-- CSS for loading map -->
	<style>
    body {
        background-color: #fafafa;
        font-family: Arial, Helvetica, sans-serif;
        margin : 300px;
    }
    div#map {
  	align-self: center;
        height: 400px;
        width: 600px;
    }
	</style>
	<!-- CSS for loading map -->

	<!-- Scripts for loading map-->
	<script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArgTbhRooDwZ7iSIG-k5NBWyocS6yvDYY&libraries=places"></script>
	<script src="{% static 'website/js/map.js' %}"></script>
	<!-- Scripts for loading map-->

	<!-- Script for sending email -->
	<script src="{% static 'website/js/smtp.js' %}"></script>
	<script src="{% static 'website/js/sendEmail.js' %}"></script>
	<!-- Script for sending email -->


	<link rel="stylesheet" href="{% static 'website/css/style.css' %}" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link rel="stylesheet" href="{% static 'website/css/font-awesome.css' %}">
	<!-- Font-Awesome-Icons-CSS -->
	<link href="{% static 'website/css/nav.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- For-Navigation-CSS -->
	<link rel="stylesheet" href="{% static 'website/css/smoothbox.css' %}" type='text/css'>
	<!-- For-Gallery-CSS -->
  <!-- online-fonts -->
	<link href="//fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i&amp;subset=latin-ext,vietnamese"
	 rel="stylesheet">
	<!-- //online-fonts -->
  <!--My StyleSheet-->
  <link rel="stylesheet" type="text/css" href="{% static 'website/css/mystylesheet.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
  <!--Top Nav Bar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!--Header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand-name" href="{% url 'website:home_view' %}">
              <img src="{% static 'website/images/sundeck_logo.png' %}" width="100" height="30"/>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav">
           <li class="{%block home_active%}  {%endblock%}"><a href="{% url 'website:home_view' %}"><span class="glyphicon glyphicon-home"></span>&nbsp; HOME</a></li>
           <li class="{%block about_active%}  {%endblock%}"><a href="{% url 'website:about_view' %}"><span class="glyphicon glyphicon-briefcase"></span>&nbsp; ABOUT US</a></li>
           <li class="{%block gallery_active%}  {%endblock%}"><a href="{% url 'website:gallery_view' %}"><span class="glyphicon glyphicon-camera"></span>&nbsp; GALLERY</a></li>
           <li class="{%block contact_active%}  {%endblock%}"><a href="{% url 'website:contact_view' %}"><span class="glyphicon glyphicon-envelope"></span>&nbsp; CONTACT US</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="{% url 'website:contact_view' %}">
                  <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>&nbsp; +91 7506087770
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
<!--Top Navbar -->

<!-- Actual Body -->
<div class="container-fluid" style="padding :0px; margin : 0px;">
  {%block body%}
  {%endblock%}
</div>
<!-- Actual Body -->
<!--Footer -->
<footer>
  <div class="w3ls-footer-grids">
			<div class="container">
				<div class="col-md-3 w3l-footer one">
					<h2>Solar Power</h2>
					<p> "The world must turn to (the) sun to power our future. As the developing world lifts billions of people into prosperity,
						our hope for a sustainable planet rests on a bold, global initiative."</p>
					<p class="adam">- Narendra Modi, Prime Minister of India</p>
					<div class="clearfix"></div>
				</div>
				<div class="col-md-3 w3l-footer agileinfo_footer_grid">
					<h3>Navigation</h3>
					<div class="nav-w3-l">
						<ul>
							<li><a href="{% url 'website:home_view' %}">Home</a></li>
							<li><a href="{% url 'website:about_view' %}">About Us</a></li>
							<!--<li><a href="#team" class="scroll" >Team</a></li>-->
							<li><a href="{% url 'website:gallery_view' %}">Gallery</a></li>
							<li><a href="{% url 'website:contact_view' %}">Contact Us</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-3 w3l-footer two">
					<h3>Keep Connected</h3>
					<ul>
						<li><a class="fb" href="https://www.facebook.com/pg/Sundeck-PV-Technology-1143472735757294"><i class="fa fa-facebook"></i>Like us on Facebook</a></li>
						<!--<li><a class="fb1" href="#"><i class="fa fa-twitter"></i>Follow us on Twitter</a></li>-->
						<li><a class="fb2" href="https://www.facebook.com/pg/Sundeck-PV-Technology-1143472735757294"><i class="fa fa-google-plus"></i>Add us on Google Plus</a></li>
						<!--<li><a class="fb3" href="#"><i class="fa fa-dribbble"></i>Follow us on Dribbble</a></li>-->
						<!--<li><a class="fb4" href="#"><i class="fa fa-pinterest-p"></i>Follow us on Pinterest</a></li>-->
					</ul>
				</div>
				<div class="col-md-3 w3l-footer three">
					<h3>Address</h3>
					<ul>
						<li><i class="fa fa-map-marker"></i>
							<p>Sundeck PV Technology <span>Sion,</span>Mumbai, Maharashtra. </p>
							<div class="clearfix"></div>
						</li>
						<li><i class="fa fa-phone"></i>
							<p>+91 7506087770</p>
							<div class="clearfix"></div>
						</li>
						<li><i class="fa fa-envelope-o"></i><a href="mailto:sundeckpv.info@gmail.com">sundeckpv.info@gmail.com</a>
							<div class="clearfix"></div>
						</li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		<div class="copy-right-grids">
			<div class="container">
				<div class="copy-left">
					<p class="footer-gd">© 2017 Sundeck PV Technology. All Rights Reserved </p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
</footer>
<!--End Footer -->
<!-- js-scripts -->

	<!-- js -->
	<script type="text/javascript" src="{% static 'website/js/jquery-2.1.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'website/js/bootstrap.js' %}"></script>
	<!-- Necessary-JavaScript-File-For-Bootstrap -->
	<!-- //js -->

	<!-- Baneer-js -->
	<script src="{% static 'website/js/responsiveslides.min.js' %}"></script>
	<script>
		// You can also use "$(window).load(function() {"
		$(function () {
			// Slideshow 4
			$("#slider4").responsiveSlides({
				auto: true,
				pager: true,
				nav: false,
				speed: 500,
				namespace: "callbacks",
				before: function () {
					$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
					$('.events').append("<li>after event fired.</li>");
				}
			});

		});
	</script>
	<script>
		// You can also use "$(window).load(function() {"
		$(function () {
			// Slideshow 4
			$("#slider3").responsiveSlides({
				auto: true,
				pager: false,
				nav: true,
				speed: 500,
				namespace: "callbacks",
				before: function () {
					$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
					$('.events').append("<li>after event fired.</li>");
				}
			});

		});
	</script>

	<!-- //Baneer-js -->

	<!-- gallery -->
	<script type="text/javascript" src="{% static 'website/js/smoothbox.jquery2.js' %}"></script>
	<!-- //gallery -->

	<!-- flexSlider -->
	<link rel="stylesheet" href="{% static 'website/css/flexslider.css' %}" type="text/css" media="screen" property="" />
	<script defer src="{% static 'website/js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript">
								$(window).load(function () {
									$('.flexslider').flexslider({
										animation: "slide",
										start: function (slider) {
											$('body').removeClass('loading');
										}
									});
								});
	</script>
	<!-- //flexSlider -->

	<!-- js for navigation -->
	<script src="{% static 'website/js/classie.js' %}"></script>
	<script src="{% static 'website/js/nav.js' %}"></script>
	<script src="{% static 'website/js/main.js' %}"></script>
	<!-- //js for navigation -->


	<!-- Stats-Number-Scroller-Animation-JavaScript -->
	<script src="{% static 'website/js/waypoints.min.js' %}"></script>
	<script src="{% static 'website/js/counterup.min.js' %}"></script>
	<script>
		jQuery(document).ready(function ($) {
			$('.counter').counterUp({
				delay: 100,
				time: 1000
			});
		});
	</script>
	<!-- //Stats-Number-Scroller-Animation-JavaScript -->


	<!-- start-smoth-scrolling -->
	<script type="text/javascript" src="{% static 'website/js/move-top.js' %}"></script>
	<script type="text/javascript" src="{% static 'website/js/easing.js' %}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
			});
		});
	</script>
	<!-- start-smoth-scrolling -->

	<!-- smooth scrolling-bottom-to-top -->
	<script type="text/javascript">
		$(document).ready(function () {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/
			$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
	<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!-- //smooth scrolling-bottom-to-top -->

	<!-- //js-scripts -->
	<script data-cfasync="false" type="text/javascript"
src="https://cdn.rawgit.com/dwyl/html-form-send-email-via-google-script-without-server/master/form-submission-handler.js"></script>

</body>
</html>

sundeckenergy/website/templates/website/contact.html
{% extends 'website/base.html' %}

{%block title%}  Contact Us | SundeckEnergy{%endblock%}
{%block contact_active%} active {%endblock%}
{%block body%}
<body onload="initialize()" onunload="GUnload()">
<script type="text/javascript" src="http://maps.google.com/maps?file=api&v=2&key=GOOGLE-MAP-API-KEY"></script>

<script type="text/javascript" >
var map = null;
var geocoder = null;
function initialize() {
      if (GBrowserIsCompatible()) {
        map = new GMap2(document.getElementById("map_contact"));
        map.setCenter(new GLatLng(19.0759837, 72.87765590000004), 15);
        map.setUIToDefault();
        geocoder = new GClientGeocoder();
      }
    }

    function showAddress(address) {
      if (geocoder) {
        geocoder.getLatLng(
          address,
          function(point) {
            if (!point) {
              alert(address + " not found");
            } else {
              map.setCenter(point, 15);
              var marker = new GMarker(point, {draggable: true});
              map.addOverlay(marker);
              GEvent.addListener(marker, "dragend", function() {
                marker.openInfoWindowHtml(marker.getLatLng().toUrlValue(6));
                document.getElementById("id_longitute").value = marker.getLatLng().lng();
                document.getElementById("id_latitude").value = marker.getLatLng().lat();
              });
              GEvent.addListener(marker, "click", function() {
                marker.openInfoWindowHtml(marker.getLatLng().toUrlValue(6));
                document.getElementById("id_longitute").value = marker.getLatLng().lng();
                document.getElementById("id_latitude").value = marker.getLatLng().lat();
              });
              document.getElementById("id_longitute").value = marker.getLatLng().lng();
              document.getElementById("id_latitude").value = marker.getLatLng().lat();
	      GEvent.trigger(marker, "click");
            }
          }
        );
      }
    }

</script>
<!-- //Contact -->
<div class="contact" id="contact">
		<div class="container">
			<h3 class="tittle">Contact Us</h3>
			<span>Get In Touch</span>

			<div class="contact-grid1">

				<div class="contact-top1">
					<div id="thankyou_message" style="display: none;">
						<label>Thanks for contacting us! We will get back to you soon!</label>
					</div>
					<form action="" method="post">
						{% csrf_token %}
					 	{% for field in form %}
							{% if field.label != "Latitude*" and field.label != "Longitude*" and field.label != "Address*" %}
								<div class="form-group">
									<label>{{field.label}}</label>
									{{field}}
								</div>
							{% endif %}
						{% endfor %}

            <label>Address*</label>
            <input type="text" name="address" required="" id="id_address" maxlength="300" placeholder="Address" onchange="showAddress(address.value);">
						<div id="map_contact" class="container-fluid"></div>
						<div class="lati" id="lat-long">
							<table class="container-fluid" id="table_lati">
								<thead>
									<tr>
										<td class="lati">
											<strong>Latitude*</strong> &nbsp;<input type="number" name="latitude" step="any" id="id_latitude" style="color: #000000">
										</td>
                    <td class="lati">
											<strong>Longitude*</strong> &nbsp;<input type="number" step="any" name="longitude" id="id_longitute" style="color: #000000">
										</td>
									</tr>
								</thead>
							</table>
						</div>

						<input type="submit" id="send" value="Send">

					</form>
				</div>
			</div>
		</div>

</div>
</body>
{%endblock%}

sundeckenergy/website/templates/website/index.html
{% extends 'website/base.html' %}
{%block title%}SundeckEnergy{%endblock%}
{%block home_active%} active {%endblock%}
{%block body%}
{%load staticfiles%}


<div class="Main-agile">
  <!-- banner -->
  <div class="sub-agile">

    <div class="col-md-12 logo">
      <h1><a href="{% url 'website:home_view' %}"><img src="{% static 'website/images/sundeck_logo.png' %}" width="200px;" height="75px;"><span> PV Technology</span></a></h1>
    </div>

    <div class="clearfix"> </div>
  </div>
  <!-- banner-text -->
  <div class="slider">
    <div class="callbacks_container">
      <ul class="rslides callbacks callbacks1" id="slider4">
        <li>
          <div class="w3layouts-banner-top banner">
            <div class="container">
              <div class="agileits-banner-info">
                <h3>SAVING <span>ENERGY</span></h3>
                <p>SAVING THE PLANET</p>
                <h5><a href="#" class="view rew3" data-toggle="modal" data-target="#myModal5"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>Learn More</a></h5>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="w3layouts-banner-top banner-2">
            <div class="container">
              <div class="agileits-banner-info">
                <h3>Solar Energy <span>System</span></h3>
                <p>save 40% On a home</p>
                <h5><a href="#" class="view rew3" data-toggle="modal" data-target="#myModal5"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>Learn More</a></h5>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="w3layouts-banner-top banner-3">
            <div class="container">
              <div class="agileits-banner-info">
                <h3>THE <span>POWER</span></h3>
                <p>OF SUN AT YOUR HOME</p>
                <h5><a href="#" class="view rew3" data-toggle="modal" data-target="#myModal5"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>Learn More</a></h5>

              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class="clearfix"> </div>
    <!-- //banner-text -->
  </div>

  <div class="header">
    <div class="col-md-6 w3l_header_left">
      <p><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <a href="mailto:sundeckpv.info@gmail.com">sundeckpv.info@gmail.com</a></p>
    </div>
    <div class="col-md-6 w3l_header_right">
      <div class="navbar-right social-icons">
        <ul>
          <li><a href="https://www.facebook.com/pg/Sundeck-PV-Technology-1143472735757294" class="fa fa-facebook icon-border facebook"> </a></li>
          <!--	<li><a href="#" class="fa fa-twitter icon-border twitter"> </a></li> -->
          <li><a href="https://plus.google.com/u/0/116680952174661961388" class="fa fa-google-plus icon-border googleplus"> </a></li>
          <!-- <li><a href="#" class="fa fa-rss icon-border rss"> </a></li> -->
        </ul>
      </div>
    </div>
    <div class="clearfix"> </div>
  </div>
</div>

<!-- Modal5 -->
<div class="modal fade" id="myModal5" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4>Solar Power </h4>
        <h5>Future of Energy Sector</h5>
        <img src="{% static 'website/images/img2.jpg' %}" alt="blog-image" />
        <span>We all know the imporatnace of energy in our day-to-day life. Everything we do, almost everything we need, is somehow or the other related to energy and electricity. In this modern era of technology, we end being so much dependent on energy resources that we don't realize how the future would be. There have been a lot of researches, giving rise to renewable energy sources, but there has been a lack of proper implementation. Many of the research studies say that renewable enrgy sources like Solar Power is the future. Currently, there are many efforts being put in to build an infrastructure, which can shift are dependance from the non-renewable to renewable energy sources. And here we are making some efforts to proceed in that direction, with a small step but an effective one for sure.</span>
      </div>
    </div>
  </div>
</div>
<!-- //Modal5 -->
{% if success_status == "success" %}
  <script>
    alert('{{contact_name}} Thank You for contacting us! We will get back to you soon!')
  </script>
{% endif %}

{%endblock%}